# Generated by Django 4.0.5 on 2022-06-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=100)),
                ('common_name', models.CharField(max_length=100)),
                ('water_use', models.CharField(max_length=50)),
                ('light', models.CharField(max_length=50)),
                ('insects', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, default=None, max_length=200)),
            ],
        ),
    ]
